name: QA Daily Tips Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # UTC time

jobs:
  send-tip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Send QA Daily Tip
        run: node index.js
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
